site_name: The Frying Saucer
site_url: https://thefryingsaucer.com
theme: 
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  logo: assets/images/FSlogo.jpg
  favicon: assets/images/FSlogo.jpg
  palette:
    primary: orange
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  
nav:
  - Home: index.md
  - Release Notes: 
      - v 0.0.1: Release-Notes/v-0.0.1.md
  - Developer Testing Assistant Guides:
      - Developer Environment Configuration Guide: Developer-Assistant-Guide\Development-Environment-Configuration-Guide.md
      - CICD Testing Developer Guide: Developer-Assistant-Guide\CICD-testing-developer-guide.md
  - The Frying Saucer (TFS) API Guide:
      - Getting Started with The Frying Saucer API: TFS-API-Guide\TFS-API-Administrator-Guide.md

markdown_extensions:
  - attr_list
  - toc: 
      toc_depth: 3
  - admonition
  - md_in_html
  - tables
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox
